### ISSUE TITLE
Sample ID / Replica merging

### ISSUE THREAD

**Issue by phegnal** [LangeLab/DataAnalysisPipeline#15]
- If one dataset has replica and the other dataset (e.g. PTM) does not some analyses fail because sample IDs don't match 
- This might not only be the case for different replica but for non fully matching sample sets in general
- merging of replica does currently not work for samples that have only one replica 
 > this should be fixed, should simply take on the name of the replica set. If this works handling samples with different number of replica should also work
 
 > Ideally also support incomplete sample sets though I have no idea what that requires.

**Comment by eneskemalergin** [comment]
This is a dynamic problem that requires tweaking with the UI and adding more options for users to provide to get more robust data input. 

I will think a bit about this issue, but in the meantime, I included intersect function to only select columns that are in the metadata id column. e.g. `intersect(meta_data[,1], colnames(data))`

**Comment by eneskemalergin** [comment]
I've added the improvements and changes to the data input and replica handling with the commit: 22e12a3

- Averaging replicas won't cause issues with non-replica data. It will simply save a single sample to average data.
- Improved averaging functions speed
- Created column name and metadata identifier intersection checker in the data input.
