### ISSUE TITLE
More comprehensive demo data is needed for fully testing

### ISSUE THREAD

**Issue by eneskemalergin** [LangeLab/DataAnalysisPipeline#3]
The current demo data for testing is not enough to be able to test all the functionality. 

The list of features I am not able to test with the demo data provided:
- Protein intensity calculator
- Checkin for replicates in metadata
- Averaging the replicates
- Standard-based QC tab
  - Batch Effect correction

I believe we need to provide peptide level data as well as the other datasets with replicates allowing for replica-based features. I also don't know what exactly is required for the standard-based QC, this needs to be clarified.

**Comment by eneskemalergin** [comment]
I will close this issue for now since we have example datasets that answer all of them except one; *standard-based QC compatible data.*

**Comment by phegnal** [comment]
We should even have the standard data.  Need to check with Anuli/Siyuan where this is at

**Comment by eneskemalergin** [comment]
Are you talking about the Pool samples?

**Comment by phegnal** [comment]
I believe so yes
