### ISSUE TITLE
condition_group in impute_data is self referenced

### ISSUE THREAD

**Issue by eneskemalergin** [LangeLab/DataAnalysisPipeline#4]
There is an interesting line in the `preprocessing. R` script in the `impute_data` function: https://github.com/LangeLab/DataAnalysisPipeline/blob/bbe86a22660442405ddb3ab6aaf02b4f192175d7/Preprocessing.R#L13
Is `condition_group` a function? 

I think it is potentially a silent bug that is not causing the code to break but giving faulty results.

**Comment by jensenchen0829** [comment]
`ind` is the index of all the rows in condition_group (which is the values of grouping variable for all the samples) equals the value of `condition_group[i]`, while the `i` denotes the sample that has a NA intensity value for current protein(or Ntermini, etc.)
